config/routes.rb
Rails.application.routes.draw do
  get 'products/new'
  get 'products/index'
  get 'products/edit'
  get 'products/show'
  get '/', to: 'welcome#home', as: 'home'
  get '/about', to: 'welcome#about', as: 'about'
  get '/contact', to: 'welcome#contact', as: 'contact'
  post '/contact', to: 'welcome#thanks', as: 'thanks'


  get '/products/new', to: 'products#new', as: :new_question
  post '/products', to: 'products#create', as: :questions
  get '/products', to:	'products#index'
  get '/products/:id', to:	'products#show', as: :product
  get '/products/:id/edit', to:	'products#edit', as: :edit_question
  patch '/products/:id', to:	'products#update'
  delete '/products/:id', to:	'products#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

# The title must be present
# The title must be unique (case insensitive)
# The price must be a number that is more than 0
# The description must be present
# The description must have at least 10 characters

validates :title, presence: true, uniqueness: {case_sensitive: false}
validates :price, numericality: {greater_than: 0}
validates :description, presence: true, length: {minimum: 10}

before_validation :default_price
before_validation :capitalize_title

def self.search(str)
  Product.where(['title ILIKE ?', "%#{str}%"])
         .or(Product.where(['description ILIKE ?', "%#{str}%"])).distinct
end

# the search method successfully returns products that contain the string. I haven't been able to order by results with a title match before the description match yet. 

private

def default_price
  self.price = 1
end

def capitalize_title
  self.title.capitalize!
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      flash[:alert] = @product.errors.full_messages
      render :new
    end
  end

  def index
  end

  def edit
  end

  def show
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def thanks
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="menu">
      <ul>
        <li><%= link_to 'Home', :home %></li>
        <li><%= link_to 'About', :about %></li>
        <li><%= link_to 'Contact Us', :contact %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/new.html.erb
<h1>Create a New Product</h1>

<div class="errors_container">
  <ul class="error_messages">
    <% @product.errors.full_messages.each do |message|%>
      <li><%=message%></li>
    <% end %>
  </ul>
</div>


<%= form_with model: @product, class: "product_form", local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.submit "Create Product" %>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h3>Need a hand? Here's how you can get in touch!</h3>


<%= form_with url: contact_path, local: true, class: "form" do |f| %>
  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.text_area :message %>
  <%= f.submit :submit%>
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

app/views/welcome/thanks.html.erb
<h2>Thanks for contacting us! We'll reach out within 1-2 business days.</h2>